### ISSUE TITLE
Crash in BugsnagEvent.m

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#846] opened 2020-10-15 05:23 UTC
### Describe the bug
We're seeing a crash of unknown cause coming from Bugsnag. This has impacted 7 customers a total of 7 times, so it's fairly rare.

### Steps to reproduce
Unknown

### Environment
* Bugsnag version: 6.1.3
* CocoaPods version: 1.9.3
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): 13.7.0, 14.0.1
* Simulator or physical device: iPhone 11
* XCode version: 11.2.1
* Swift version (if applicable): 5.1

### Stack Trace

<details><summary>Stack trace:</summary>

```
Crashed: MyQueue
0  libobjc.A.dylib                0x186892b30 objc_msgSend + 16
1  Foundation                     0x186e9a3b8 -[NSArray(NSKeyValueCoding) valueForKey:] + 376
2  Foundation                     0x186ea57f8 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 428
3  MyApp                           0x1012790ac -[BugsnagEvent serializeBreadcrumbs] + 630 (BugsnagEvent.m:630)
4  MyApp                           0x101279a04 -[BugsnagEvent toJson] + 756 (BugsnagEvent.m:756)
5  MyApp                           0x10126d180 -[BugsnagClient notifyInternal:block:] + 1046 (BugsnagClient.m:1046)
6  MyApp                           0x10126cf78 -[BugsnagClient notify:handledState:block:] + 1011 (BugsnagClient.m:1011)
7  MyApp                           0x10126c1a0 -[BugsnagClient notifyError:block:] + 882 (BugsnagClient.m:882)
8  MyApp                           0x10126463c +[Bugsnag notifyError:block:] + 136 (Bugsnag.m:136)
9  MyApp                           0x101d28a68 specialized BugsnagLogStoreWriter.write(level:message:parameters:) + 4395485800 (<compiler-generated>:4395485800)
10 MyApp                           0x101d1b6b8 AggregateLogStoreWriter.write(level:message:parameters:) + 4395431608 (<compiler-generated>:4395431608)
11 MyApp                           0x101d1b778 protocol witness for LogStoreWriter.write(level:message:parameters:) in conformance AggregateLogStoreWriter + 4395431800 (<compiler-generated>:4395431800)
12 MyApp                           0x101d21e30 Logger.log(level:_:parameters:) + 4395458096 (<compiler-generated>:4395458096)
13 MyApp                           0x101bf9974 closure #1 in RedactedType1.redactedMethod + 4394244468 (<compiler-generated>:4394244468)
14 MyApp                           0x101ef5e50 RedactedType3.redactedMethod + 318 (RedactedType3.swift:318)
15 MyApp                           0x100cf3f98 protocol witness for RedactedType2.redactedMethod in conformance RedactedType3 + 4378492824 (<compiler-generated>:4378492824)
16 MyApp                           0x101bf8e30 closure #1 in closure #1 in RedactedType1.redactedMethod + 305 (RedactedType1.swift:305)
17 MyApp                           0x100ba5898 thunk for @escaping @callee_guaranteed () -> () + 4377122968 (<compiler-generated>:4377122968)
18 libdispatch.dylib              0x1868399a8 _dispatch_call_block_and_release + 24
19 libdispatch.dylib              0x18683a524 _dispatch_client_callout + 16
20 libdispatch.dylib              0x1867e68a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
21 libdispatch.dylib              0x1867e7294 _dispatch_lane_invoke$VARIANT$mp + 416
22 libdispatch.dylib              0x1867f078c _dispatch_workloop_worker_thread + 588
23 libsystem_pthread.dylib        0x18688bb74 _pthread_wqthread + 272
24 libsystem_pthread.dylib        0x18688e740 start_wqthread + 8
```
</details>

**Comment by xander-jones** [comment] 2020-10-15 14:34
Hey @sethfri, looks like there could be an issue here. We'll take a look into it. If you do stumble across a method to reproduce this, please let us know.

**Comment by mattdyoung** [comment] 2020-10-22 17:38
Hi @sethfri 

This and https://github.com/bugsnag/bugsnag-cocoa/issues/845 appear to be due to concurrency issues storing breadcrumbs.

These timing issues have occurred in a few events. We're aiming to work on a fix for this in our next sprint.

**Comment by nickdowell** [comment] 2020-10-29 08:18
This issue has been fixed in release [v6.2.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.3)

**Comment by sethfri** [comment] 2020-11-16 09:07
@mattdyoung @nickdowell @phillipsam We have seen 161 more instances of this crash since upgrading to Bugsnag 6.2.3. Could you please reopen this issue?

Here's the latest stack trace:

<details><summary>Stack trace:</summary>

```
Crashed: InvitableContactManager_Typeahead_Queue
SIGBUS 0x0000001996fb7490
0  libobjc.A.dylib                0x1b71d7978 objc_msgSend + 24
1  Foundation                     0x1a433a444 -[NSArray(NSKeyValueCoding) valueForKey:] + 380
2  Foundation                     0x1a4344744 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 432
3  MyApp                           0x100ac155c -[BugsnagEvent serializeBreadcrumbs] + 630 (BugsnagEvent.m:630)
4  MyApp                           0x100ac1df4 -[BugsnagEvent toJson] + 758 (BugsnagEvent.m:758)
5  MyApp                           0x100ab56e8 -[BugsnagClient notifyInternal:block:] + 1098 (BugsnagClient.m:1098)
6  MyApp                           0x100ab54e0 -[BugsnagClient notify:handledState:block:] + 1063 (BugsnagClient.m:1063)
7  MyApp                           0x100ab4708 -[BugsnagClient notifyError:block:] + 934 (BugsnagClient.m:934)
8  MyApp                           0x100aac750 +[Bugsnag notifyError:block:] + 147 (Bugsnag.m:147)
9  MyApp                           0x1015a52f8 specialized BugsnagLogStoreWriter.write(level:message:parameters:) + 4359115512 (<compiler-generated>:4359115512)
10 MyApp                           0x101596de0 AggregateLogStoreWriter.write(level:message:parameters:) + 4359056864 (<compiler-generated>:4359056864)
11 MyApp                           0x101596ea0 protocol witness for LogStoreWriter.write(level:message:parameters:) in conformance AggregateLogStoreWriter + 4359057056 (<compiler-generated>:4359057056)
12 MyApp                           0x10159d558 Logger.log(level:_:parameters:) + 4359083352 (<compiler-generated>:4359083352)
13 MyApp                           0x101473c1c closure #1 in Type1.personAutocompletionItems(forQuery:) + 4357864476 (<compiler-generated>:4357864476)
14 MyApp                           0x101774f10 Type2.uniqueAutocompletionItemsForSearchTerms(in:passingTest:) + 318 (Type2.swift:318)
15 MyApp                           0x1004ec0b4 protocol witness for AutocompleteResultsProvider.uniqueAutocompletionItemsForSearchTerms(in:passingTest:) in conformance Type2 + 4341579956 (<compiler-generated>:4341579956)
16 MyApp                           0x1014730d8 closure #1 in closure #1 in Type1.queryTypeaheadResults(withQuery:completionHandler:) + 305 (Type1.swift:305)
17 MyApp                           0x10038d828 thunk for @escaping @callee_guaranteed () -> () + 4340144168 (<compiler-generated>:4340144168)
18 libdispatch.dylib              0x1a2ceafd0 _dispatch_call_block_and_release + 32
19 libdispatch.dylib              0x1a2cecac8 _dispatch_client_callout + 20
20 libdispatch.dylib              0x1a2cf3c08 _dispatch_lane_serial_drain + 580
21 libdispatch.dylib              0x1a2cf4734 _dispatch_lane_invoke + 408
22 libdispatch.dylib              0x1a2cfe528 _dispatch_workloop_worker_thread + 708
23 libsystem_pthread.dylib        0x1eafdf908 _pthread_wqthread + 276
24 libsystem_pthread.dylib        0x1eafe677c start_wqthread + 8
```
</details>

**Comment by sethfri** [comment] 2020-11-16 15:01
@johnkiely1 Pinging you here as well since you triaged the rest of the issues I just opened 🙏🏻

**Comment by sethfri** [comment] 2020-11-19 00:23
I was wrong, that version of our app was using 6.2.1, not 6.2.3. Closing and will reopen if we see this again from 6.2.3

**Comment by sethfri** [comment] 2020-11-23 06:32
We are now definitely seeing this on 6.2.3. Seeing a bit more info in Bugsnag on the type of crash than I was seeing in Crashlytics before:

```
NSUnknownKeyException · [<__NSCFString 0x15a140cf0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key objectValue.
```

**Comment by sethfri** [comment] 2020-11-23 06:37
It actually looks like there are two different types of crashes still happening in 6.2.3, both with what appear to be the same stack trace. The other crash type is

```
Attempted to dereference garbage pointer 0xc0ce86890.
```

**Comment by nickdowell** [comment] 2020-11-23 09:22
Hi @sethfri I cannot find any crashes of this type for your latest app release 3.27.1 (3271005) in the Bugsnag dashboard.

If you could send us links to any errors in your Bugsnag dashboard, that would help our investigation. Thanks.

**Comment by sethfri** [comment] 2020-11-23 09:29
Hi nickdowell, 3.27.1 hasn't been out long, try 3.27. If you still can't find it, happy to grab them in the morning Pacific Time. Thanks!

**Comment by sethfri** [comment] 2020-11-23 22:21
Hi @nickdowell I sent this over via Zendesk (28612)

**Comment by sethfri** [comment] 2020-12-15 06:50
Hi there, any update on this one?

**Comment by nickdowell** [comment] 2020-12-15 10:36
Hi @sethfri, this crash originated in the breadcrumbs code which was refactored in [v6.2.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.3) to remove the possibility of concurrency related crashes.

Some crashes of this type continued being reported against more recent app versions containing 6.2.3+ because of a bug where Bugsnag reported the version number of the reporting app, rather than the crashed app.

In [v6.3.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.3.0) we fixed the app version bug, so expect you should not see any crashes of this type reported against recent app builds that contain 6.3.0 or later - if you do, please let us know!

**Comment by nickdowell** [comment] 2021-03-10 09:53
Closing this issue because the fix does appear to have worked.

If you do see this start happening again let us know and we can re-investigate.

**Closed by nickdowell** 2021-03-10 09:53 UTC
Labels: bug, released
