### ISSUE TITLE
Crash in BSG_RFC3339DateTool.m

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#872] opened 2020-10-29 17:44 UTC
### Describe the bug
We are seeing 3 crashes in BSG_RFC3339DateTool.m. Stack trace attached.

### Steps to reproduce
Unknown

### Environment
* Bugsnag version: 6.2.1
* CocoaPods version: 1.9.3
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): 14.0.1
* Simulator or physical device: iPhone 11
* Xcode version: 11.2.1
* Swift version (if applicable): 5.1

### Stack Trace

<details><summary>Stack trace:</summary>

```
Crashed: com.apple.main-thread
0  libicucore.A.dylib             0x1abd049dc icu::numparse::impl::AffixPatternMatcher::operator==(icu::numparse::impl::AffixPatternMatcher const&) const
1  libicucore.A.dylib             0x1abd089e4 icu::numparse::impl::NumberParserImpl::createParserFromProperties(icu::number::impl::DecimalFormatProperties const&, icu::DecimalFormatSymbols const&, bool, UErrorCode&)
2  libicucore.A.dylib             0x1abca50c8 icu::DecimalFormat::getParser(UErrorCode&) const
3  libicucore.A.dylib             0x1abca4f80 icu::DecimalFormat::parse(icu::UnicodeString const&, icu::Formattable&, icu::ParsePosition&) const
4  libicucore.A.dylib             0x1abd51498 icu::SimpleDateFormat::parseInt(icu::UnicodeString const&, icu::Formattable&, int, icu::ParsePosition&, signed char, icu::NumberFormat const*) const
5  libicucore.A.dylib             0x1abd4eb34 icu::SimpleDateFormat::subParse(icu::UnicodeString const&, int&, char16_t, int, signed char, signed char, signed char*, int&, icu::Calendar&, int, icu::MessageFormat*, UTimeZoneFormatTimeType*, int*) const
6  libicucore.A.dylib             0x1abd4dec8 icu::SimpleDateFormat::parse(icu::UnicodeString const&, icu::Calendar&, icu::ParsePosition&) const
7  libicucore.A.dylib             0x1abd7bb24 udat_parseCalendar
8  CoreFoundation                 0x1abe65cc4 CFDateFormatterGetAbsoluteTimeFromString
9  CoreFoundation                 0x1abe65a5c CFDateFormatterCreateDateFromString
10 Foundation                     0x1ad1ce61c getObjectValue
11 Foundation                     0x1ad172cb4 -[NSDateFormatter getObjectValue:forString:errorDescription:]
12 Foundation                     0x1ad172bb0 -[NSDateFormatter dateFromString:]
13 MyApp                           0x105070220 +[BSG_RFC3339DateTool dateFromString:] + 62 (BSG_RFC3339DateTool.m:62)
14 MyApp                           0x10508e60c -[BugsnagSession initWithDictionary:] + 101 (BugsnagSession.m:101)
15 MyApp                           0x1050906b0 -[BugsnagSessionTrackingApiClient deliverSessionsInStore:] + 63 (BugsnagSessionTrackingApiClient.m:63)
16 MyApp                           0x10508fae8 -[BugsnagSessionTracker startNewSessionWithAutoCaptureValue:] + 186 (BugsnagSessionTracker.m:186)
17 MyApp                           0x105079068 -[BugsnagClient start] + 607 (BugsnagClient.m:607)
18 MyApp                           0x105072444 +[Bugsnag startWithConfiguration:] + 93 (Bugsnag.m:93)
19 MyApp                           0x1046e77c0 -[DualCrashReporter setUpDualCrashHandler] + 41 (DualCrashReporter.m:41)
20 MyApp                           0x104ad986c AppDelegate.setUp(_:) (<compiler-generated>)
21 MyApp                           0x104addcac AppDelegate.application(_:willFinishLaunchingWithOptions:) + 656 (AppDelegate.swift:656)
22 Cash                           0x104adf220 @objc AppDelegate.application(_:willFinishLaunchingWithOptions:)
23 UIKitCore                      0x1ae8389d8 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
24 UIKitCore                      0x1ae83aac4 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]
25 UIKitCore                      0x1ae840478 -[UIApplication _runWithMainScene:transitionContext:completion:]
26 UIKitCore                      0x1aded1d70 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
27 UIKitCore                      0x1ae41d4d4 _UIScenePerformActionsWithLifecycleActionMask
28 UIKitCore                      0x1aded28c0 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
29 UIKitCore                      0x1aded238c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
30 UIKitCore                      0x1aded26d0 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
31 UIKitCore                      0x1aded1f48 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
32 UIKitCore                      0x1adeda078 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
33 UIKitCore                      0x1ae32fc28 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
34 UIKitCore                      0x1ae435810 _UISceneSettingsDiffActionPerformChangesWithTransitionContext
35 UIKitCore                      0x1aded9df0 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
36 UIKitCore                      0x1add0eeb0 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
37 UIKitCore                      0x1add0d86c -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
38 UIKitCore                      0x1add0ead8 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
39 UIKitCore                      0x1ae83e668 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
40 UIKitCore                      0x1ae358274 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
41 FrontBoardServices             0x1baed42dc -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:]
42 FrontBoardServices             0x1baefea00 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.200
43 FrontBoardServices             0x1baee2d24 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
44 FrontBoardServices             0x1baefe6d0 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke
45 libdispatch.dylib              0x1abb20ac8 _dispatch_client_callout
46 libdispatch.dylib              0x1abb24348 _dispatch_block_invoke_direct
47 FrontBoardServices             0x1baf260e0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
48 FrontBoardServices             0x1baf25d88 -[FBSSerialQueue _targetQueue_performNextIfPossible]
49 FrontBoardServices             0x1baf262ac -[FBSSerialQueue _performNextFromRunLoopSource]
50 CoreFoundation                 0x1abe9f81c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
51 CoreFoundation                 0x1abe9f718 __CFRunLoopDoSource0
52 CoreFoundation                 0x1abe9ea28 __CFRunLoopDoSources0
53 CoreFoundation                 0x1abe98d20 __CFRunLoopRun
54 CoreFoundation                 0x1abe984bc CFRunLoopRunSpecific
55 GraphicsServices               0x1c291d820 GSEventRunModal
56 UIKitCore                      0x1ae83c734 -[UIApplication _run]
57 UIKitCore                      0x1ae841e10 UIApplicationMain
58 MyApp                           0x1047326d0 main + 65 (AppDelegate.swift:65)
59 libdyld.dylib                  0x1abb5fe60 start
```
</details>

**Comment by johnkiely1** [comment] 2020-10-30 00:10
Hi @sethfri 

Thanks for reporting this, we are taking a look into this and update you as soon as we know more.

**Comment by nickdowell** [comment] 2020-10-30 16:26
Hi @sethfri if there is any more information about the crash that you could share - e.g. the exception or signal type and memory address for `EXC_BAD_ACCESS` - that would be helpful for our investigation, thanks!

**Comment by sethfri** [comment] 2020-10-31 01:20
@nickdowell Sorry about that! Idk why Crashlytics doesn't copy that part

```
Crashed: com.apple.main-thread
SIGILL 0x00000001abd049dc
```

**Comment by nickdowell** [comment] 2020-11-05 11:23
Hi @sethfri thanks for the additional information.

Having examined the crash report and source of the [crashing](https://github.com/unicode-org/icu/blob/release-66-1/icu4c/source/i18n/numparse_affixes.cpp#L223-L225) [code](https://github.com/unicode-org/icu/blob/release-66-1/icu4c/source/i18n/numparse_impl.cpp#L81-L214) it's not obvious what caused the crash, but the crash is definitely occurring in [libicucore](https://github.com/unicode-org/icu) (the Unicode library included in iOS.)

We cannot find anything in the Bugsnag notifier that could be responsible for the crash - we always pass the [same static date formats](https://github.com/bugsnag/bugsnag-cocoa/blob/d2560bbc5d672727368015284a44adc26d6ae4d8/Bugsnag/Helpers/BSG_RFC3339DateTool.m#L42-L55) to `NSDateFormatter` and [ensure we're passing in a string](https://github.com/bugsnag/bugsnag-cocoa/blob/d2560bbc5d672727368015284a44adc26d6ae4d8/Bugsnag/Helpers/BSG_RFC3339DateTool.m#L67-L69) so bad input does not seem to be the cause.

The rarity of occurrences of this crash suggests something like memory corruption may have occurred. It could also be a bug in libicucore as we do see a small number of crashes originating from this library (not all with Bugsnag in the stack trace) reported from a variety of apps.

**Comment by mattdyoung** [comment] 2020-11-19 10:30
Closing as we believe this is either some form of memory corruption, or a bug in libicucore rather than a bug in Bugsnag.

**Closed by mattdyoung** 2020-11-19 10:30 UTC
