### ISSUE TITLE
[ERROR] Failed to install crash handler. No exceptions will be reported!

### ISSUE THREAD

**Issue by vmagnani** [bugsnag/bugsnag-cocoa#1139] opened 2021-06-28 12:30 UTC
Please checkout our [documentation](https://docs.bugsnag.com/platforms/ios/) for guides, references and tutorials.

If you have questions about your integration please contact us at [support@bugsnag.com](mailto:support@bugsnag.com).

Alternatively, view additional options at [support.md](../SUPPORT.md).

Dears, good morning!

I have this error in the debug:

[Bugsnag] [ERROR] Failed to install crash handler. No exceptions will be reported!

Can you give me a light on what I'm missing?

I`m using objective c.

Thanks so much.

**Comment by yousif-bugsnag** [comment] 2021-06-28 16:44
Hi @vmagnani,

The error message you're seeing is a bit misleading - it just means that due to the current configuration / environment there wasn't a crash handler to install. We have actually removed this message in https://github.com/bugsnag/bugsnag-cocoa/pull/1091 (released in [v6.9.2](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.9.2))

Closing this issue as we believe it's already been fixed, but if you're still experiencing this issue on 6.9.2 or greater do let us know and we'd be happy to investigate further.

**Closed by yousif-bugsnag** 2021-06-28 16:44 UTC

**Comment by vmagnani** [comment] 2021-06-28 17:19
@yousif-bugsnag thanks for the answer, but I forgot to mention that I'm using version 6.9.6.

I'm a little more relieved to know that it's not a problem.

**Comment by pandaApe** [comment] 2021-07-22 05:19
we are still facing this issue on v6.10.2, pls help take a look!

**Comment by mattdyoung** [comment] 2021-07-23 09:54
@pandaApe - could you write in to support@bugsnag.com with full details of how you're configuring Bugsnag in code and what the issue is you're seeing? i.e. is it just that you're seeing that warning or are crashes not being reported?
