### ISSUE TITLE
SIGPIPE in BSSerializeJSONDictionary

### ISSUE THREAD

**Issue by rebello95** [bugsnag/bugsnag-cocoa#656] opened 2020-06-01 16:53 UTC
### Description
We've seen a crash when adding metadata to the Bugsnag SDK, which appears to be happening in the `BSSerializeJSONDictionary` function when adding/updating attributes in the SDK.

### Issue

When calling `+[Bugsnag addAttribute:withValue:toTabWithName:]`, we are occasionally seeing a `SIGPIPE` crash (shown below).

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): 5.22.10
* iOS/tvOS/macOS version(s): iOS 12/13
* debug mode or production?: Production
* How are you initializing Bugsnag?

```
let configuration = BugsnagConfiguration()
configuration.apiKey = key
configuration.automaticallyCollectBreadcrumbs = false
configuration.shouldAutoCaptureSessions = true
configuration.add(beforeSend: { [weak self] _, report in
    report.addAttribute("session", withValue: ..., toTabWithName: ...)
    self?.willSendReport(report)
    return true
})
configuration.setUser(..., withName: nil, andEmail: nil)
for (key, value) in attributes {
    configuration.metaData?.addAttribute(key, withValue: value, toTabWithName: ...)
}

configuration.releaseStage = ...
Bugsnag.start(with: configuration)
Bugsnag.setBreadcrumbCapacity(100)
Bugsnag.payloadDateFormatter().dateFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.SSSSZZZ"
```

### Stack trace

```
SIGPIPE
BSSerializeJSONDictionary

May 29th, 2020, 18:55:52 UTC

STACKTRACE

CrashReporter Key:  f1fb98aa2caba34f5e7fa0f5e7c1906e5310bb6a
Hardware Model:     iPhone11,8
Process:            Lyft
Identifier:         com.zimride.instant
Version:            6.33.3
OS Version:         iOS 13.3.1



SIGPIPE: 

0  Foundation        __convertJSONString
1  Foundation        __writeJSONString
2  Foundation        ____writeJSONObject_block_invoke
3  Foundation        ____writeJSONObject_block_invoke_2
4  CoreFoundation    ___NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
5  CoreFoundation    -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
6  Foundation        __writeJSONObject
7  Foundation        ____writeJSONObject_block_invoke
8  Foundation        ____writeJSONObject_block_invoke_2
9  CoreFoundation    ___NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
10 CoreFoundation    -[__NSFrozenDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
11 Foundation        __writeJSONObject
12 Foundation        -[_NSJSONWriter dataWithRootObject:options:error:]
13 Foundation        +[NSJSONSerialization dataWithJSONObject:options:error:]
14 Lyft              BSSerializeJSONDictionary (Lyft)
15 Lyft              -[BugsnagNotifier metaDataChanged:] (Lyft)
16 Lyft              -[BugsnagMetaData addAttribute:withValue:toTabWithName:] (Lyft)
17 Lyft              +[Bugsnag addAttribute:withValue:toTabWithName:] (Lyft)
```

**Comment by snmaynard** [comment] 2020-06-01 19:21
I've had a quick look at this, and I don't see how `+[NSJSONSerialization dataWithJSONObject:options:error:]` can generate a `SIGPIPE`. My only thought is that something you are adding to the metadata is doing something unusual when serialized to json? Perhaps you are trying to serialize a socket somehow or equivalent? Can you take a look at what is being added to the metadata to generate this crash to see if an explanation lies in that?  I assume from your description that you are able to reproduce this? If not let me know and I will think about how we can capture what is going on.

**Comment by rebello95** [comment] 2020-06-01 20:25
> My only thought is that something you are adding to the metadata is doing something unusual when serialized to json? Perhaps you are trying to serialize a socket somehow or equivalent? Can you take a look at what is being added to the metadata to generate this crash to see if an explanation lies in that?

Looking through our stacktraces, this appears to be happening when we set a string key + string value to the `app` tab, so these are primitives.

> I assume from your description that you are able to reproduce this? If not let me know and I will think about how we can capture what is going on.

We haven't been able to reproduce this unfortunately 😞 the volume hasn't been very high overall (maybe there's a race somewhere in Bugsnag code?)

**Comment by phillipsam** [comment] 2020-06-30 17:20
Hi @rebello95 Unfortunately there is not much more we can look into on this if we are unable to reproduce it. I am closing this for now, but please let us know if this you are able to find a reproduction case for this.

**Closed by phillipsam** 2020-06-30 17:20 UTC
