### ISSUE TITLE
Occasional mangled stacktrace 

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#196] opened 2017-10-23 12:01 UTC
### Expected behavior
Stacktraces on errors represent actual call stacks in the application code.

### Observed behavior
It doesn't happen often, but I've seen a few stacktraces that are totally mangled.  The method names are a mashup of a bunch of seemingly random symbols from my app, with random characters in betwee.  It happened twice when I was running bugsnag-cocoa 5.10.1:
https://app.bugsnag.com/recharge-labs/ios/errors/59d1981acecef50018b6df99
https://app.bugsnag.com/recharge-labs/ios/errors/59cf0984d17ce8001b65ed34

...but it stopped happening so I wrote it off as a fluke of the KSCrash work that happened around that release (thanks again for that!)

But yesterday it happened again, on 5.13.0:
https://app.bugsnag.com/recharge-labs/ios/errors/59eb8bbf104d8a00190e3872

### Steps to reproduce
No idea

### Version
5.10.1, 5.13.0

**Comment by fractalwrench** [comment] 2017-10-23 13:01
Thanks for the report @edenman. The only obvious common features between those errors is that they seem to all start with `_T`, and that the thread trace is mangled for Swift but not Objective-C (i.e. 2nd error report).

I've passed this onto our backend team, so will let you know the outcome of their investigations.

**Comment by fractalwrench** [comment] 2017-10-24 09:36
@edenman it looks like there was an issue with how our backend was processing frames starting with `_T` - we've deployed a fix for this. Many thanks for the report, feel free to get in touch if you run into anything else!

**Comment by edenman** [comment] 2017-10-25 03:51
So...I was super happy with the response time on this, I even shared it with my team to show how happy I've been with you guys.

...but it seems like something is still screwy:
https://app.bugsnag.com/recharge-labs/ios/errors/59eff66bcbdf860018b6619c?event_id=59eff66bcbdf860018b6619b&i=em&m=nw
this is from a TestFlight build before I had uploaded the dSYMs, so maybe it's specific to that case?  This one was parsed just fine (after I uploaded dSYMs):
https://app.bugsnag.com/recharge-labs/ios/errors/59d68a7787c47d001b2a7fb9?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=fixed&event_id=59f0087a6c868a001a5060b5

**Comment by fractalwrench** [comment] 2017-10-25 10:25
Sorry about that @edenman. I've been informed by our backend team that the linked error report was demangled correctly, but uploading the dSYM triggered symbolication, where our code was out of date and didn't process the frames correctly.

A fix has been deployed so that all future errors should be deobfuscated correctly - please let us know if that's not the case!

**Comment by edenman** [comment] 2017-10-30 17:30
happened again https://app.bugsnag.com/recharge-labs/ios/errors/59f541108ce4cd0018fb6e24

**Comment by fractalwrench** [comment] 2017-10-31 11:58
Sorry to hear that @edenman - do you know which version of Swift you're using? I don't suppose you have any idea what code might be causing that error? We can definitely see that this is an issue but are having trouble narrowing down a reproducible test case.

**Comment by edenman** [comment] 2017-10-31 18:32
Swift4.  And no, unfortunately no idea what could be causing it :/

**Comment by edenman** [comment] 2017-11-01 16:56
one more, in case it's helpful for tracking down the root cause: https://app.bugsnag.com/recharge-labs/ios/errors/59f9c78331c9ef0018f2618c (this one has a bunch of `direct field offset for` prefixes on the symbol names)

**Comment by edenman** [comment] 2018-01-10 23:31
Haven't seen any of these lately, fwiw

**Comment by fractalwrench** [comment] 2018-01-25 09:42
Closing this for now as it hasn't been observed recently. Feel free to comment if it occurs again and we'll reopen this.

**Closed by fractalwrench** 2018-01-25 09:42 UTC
