### ISSUE TITLE
undeclared use of _id, _email when building in xcode

### ISSUE THREAD

**Issue by inctor** [bugsnag/bugsnag-cocoa#947] opened 2020-12-17 13:08 UTC
### Describe the bug
When following instructions from here: https://docs.bugsnag.com/platforms/ios/symbolication-guide/ the build process fails in xCode.

### Steps to reproduce
1. Follow instructions in link, and try to build in xCode

### Environment
* Bugsnag version: 6.4.1
* CocoaPods version: 1.9.3
* iOS/tvOS/macOS version(s): 12
* Simulator or physical device: Both
* Xcode version: 12.01

![Screenshot 2020-12-17 at 14 05 34](https://user-images.githubusercontent.com/1939469/102492031-58c94680-4071-11eb-9214-406c12b7a766.png)

**Comment by yousif-bugsnag** [comment] 2020-12-18 14:25
Hi @inctor, we haven't been able to reproduce this. Have you tried clearing your cache? We've seen Cocoapods lose entire source files sometimes, and found that deleting `~/Library/Caches/CocoaPods` can help. Let us know if that makes any difference.

**Comment by mattdyoung** [comment] 2021-01-18 22:01
Closing as we haven't received a response, but if this is still causing issues then please share further details on how to reproduce the issue and we can re-open.

**Comment by inctor** [comment] 2021-01-29 14:20
Hey @yousif-bugsnag and @mattdyoung , 
i tried looking into it again, but the issue still occurs.. 
i tried deleting caches and removing all installed pods, and also all node_modules, and reinstall it all, but the issue still occurs.

I followed this guide: https://docs.bugsnag.com/platforms/react-native/react-native/
and then the iOS Symbolication guide here: https://docs.bugsnag.com/platforms/ios/symbolication-guide/

I've attached pictures of the errors that occur.. Can you help?


<img width="531" alt="Screenshot 2021-01-29 at 15 18 51" src="https://user-images.githubusercontent.com/1939469/106286045-834c1900-6245-11eb-9bdd-1ca66ccafff1.png">
<img width="545" alt="Screenshot 2021-01-29 at 15 18 37" src="https://user-images.githubusercontent.com/1939469/106286058-85ae7300-6245-11eb-97c5-d237c49c2d8c.png">
<img width="1261" alt="Screenshot 2021-01-29 at 15 16 18" src="https://user-images.githubusercontent.com/1939469/106286060-86470980-6245-11eb-9ff6-970eca7de52f.png">
<img width="1920" alt="Screenshot 2021-01-29 at 15 15 50" src="https://user-images.githubusercontent.com/1939469/106286064-8810cd00-6245-11eb-8a7f-88a501bdecf1.png">

**Comment by mattdyoung** [comment] 2021-02-01 15:20
@inctor 
It looks like this is for a React Native project - can you confirm?

If so can you let us know which version of React Native you're using and which version of [bugsnag-js](https://github.com/bugsnag/bugsnag-js/releases) you've integrated?

Do you see the same issue if you create a new React Native project and integrate Bugsnag in the same way?

If you have a reproduction example you can share that would help us diagnose. You can email us at support@bugsnag.com if you don't want to share this publicly on the issue.

**Comment by mattdyoung** [comment] 2021-02-19 13:55
Closing this as we haven't been able to reproduce the error you're seeing, but if you have a reproduction case you can share with us we'd be happy to re-open and investigate further.

**Closed by mattdyoung** 2021-02-19 13:55 UTC
