### ISSUE TITLE
Crash in bsg_kscrashsentry_resume_threads_user.cold.1

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#850] opened 2020-10-19 02:20 UTC
### Describe the bug
We're seeing a crash of unknown cause coming from Bugsnag. This has impacted 1 customer 3 times, and we are only seeing it in Crashlytics, not Bugsnag.

### Steps to reproduce
Unknown

### Environment
* Bugsnag version: 6.1.3
* CocoaPods version: 1.9.3
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): 14.0.1 (18A393)
* Simulator or physical device: iPhone 11
* XCode version: 11.2.1
* Swift version (if applicable): 5.1

### Stack Trace

<details><summary>Stack trace:</summary>

```
Crashed: MyQueue (QOS: UNSPECIFIED)
0  MyApp                           0x103ef8700 bsg_kscrashsentry_resume_threads_user.cold.1 + 4393879296
1  MyApp                           0x103a3d06c specialized Array.append<A>(contentsOf:) + 4388917356 (<compiler-generated>:4388917356)
2  MyApp                           0x103a3c45c Array.appending(contentsOf:) + 23 (Array+CCAdditions.swift:23)
3  MyApp                           0x103a10ee8 closure #1 in MyType.myMethod + 517 (MyType.swift:517)
4  MyApp                           0x1026bd898 thunk for @escaping @callee_guaranteed () -> () + 4368472216 (<compiler-generated>:4368472216)
5  Foundation                     0x1a334a7f4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
6  Foundation                     0x1a323d120 -[NSBlockOperation main] + 104
7  Foundation                     0x1a334cbb8 __NSOPERATION_IS_INVOKING_MAIN__ + 24
8  Foundation                     0x1a323cda8 -[NSOperation start] + 808
9  Foundation                     0x1a334d624 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
10 Foundation                     0x1a334d0d0 __NSOQSchedule_f + 184
11 libdispatch.dylib              0x1a1c3e834 _dispatch_block_async_invoke2 + 148
12 libdispatch.dylib              0x1a1c30ac8 _dispatch_client_callout + 20
13 libdispatch.dylib              0x1a1c33d60 _dispatch_continuation_pop + 416
14 libdispatch.dylib              0x1a1c33494 _dispatch_async_redirect_invoke + 592
15 libdispatch.dylib              0x1a1c41104 _dispatch_root_queue_drain + 356
16 libdispatch.dylib              0x1a1c418e8 _dispatch_worker_thread2 + 116
17 libsystem_pthread.dylib        0x1e958c8cc _pthread_wqthread + 216
18 libsystem_pthread.dylib        0x1e959377c start_wqthread + 8
```
</details>

**Comment by nickdowell** [comment] 2020-10-27 15:10
Hi @sethfri thanks for the crash report.

The very large offset (`+ 4393879296`) in this stack trace suggests that the crash did not actually occur in the indicated function, and that something has gone wrong in the symbolication - `bsg_kscrashsentry_resume_threads_user` is a small function and there’s no way an offset that large could be valid.

This is backed up when we try to manually symbolicate the stack frames:

```
atos -o 0F84437B-A6D9-3C53-8D95-858E4E8BF822 -s 0x2430000 0x103ef8700 -> 0x0000000101ac8700
atos -o 0F84437B-A6D9-3C53-8D95-858E4E8BF822 -s 0x2430000 0x103a3d06c -> specialized Array.append<A>(contentsOf:) (<compiler-generated>:0)
atos -o 0F84437B-A6D9-3C53-8D95-858E4E8BF822 -s 0x2430000 0x103a3c45c -> Array.appending(contentsOf:) (Array+CCAdditions.swift:23)
atos -o 0F84437B-A6D9-3C53-8D95-858E4E8BF822 -s 0x2430000 0x103a10ee8 -> closure #1 in CCPersonManager.peopleDidChange() (CCPersonManager.swift:517)
atos -o 0F84437B-A6D9-3C53-8D95-858E4E8BF822 -s 0x2430000 0x1026bd898 -> thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)
```

As you can see, the frames match up except for the first one. It looks like Crashlytics has incorrectly symbolicated the first frame in this instance.

What may have happened is a jump to a memory location that doesn’t contain valid executable code, resulting in the `EXC_BAD_INSTRUCTION` exception. This can be caused by stack corruption such as overwriting the return address.

**Comment by mattdyoung** [comment] 2020-11-19 10:25
Closing as we believe this is a consequence of some form of memory corruption rather than a bug.

**Closed by mattdyoung** 2020-11-19 10:25 UTC
