### ISSUE TITLE
[BSGAppHangDetector startWithDelegate:] crash

### ISSUE THREAD

**Issue by ericcj** [bugsnag/bugsnag-cocoa#1562] opened 2023-06-08 18:22 UTC
### Describe the bug

Definitely less than 1% of sessions but potentially a dispatch_semaphore issue causing bugsnag to crash the app 

<img width="1291" alt="Screenshot 2023-06-08 at 2 19 41 PM" src="https://github.com/bugsnag/bugsnag-cocoa/assets/53106/0f19e452-1b0f-4f06-bbcc-7d7a9a870925">

**Comment by ericcj** [comment] 2023-06-09 13:04
thanks!    pod 'Bugsnag',  '~> 6.25.0'

**Comment by johnkiely1** [comment] 2023-06-16 08:05
Hi @ericcj, Thanks.

 It's quite difficult to tell with confidence, but after some investigation this feels more like an OS bug because `dispatch_semaphore_signal` should not break like that unless the semaphore itself is NULL but the semaphore gets created earlier in the same function, so that should not be possible. Maybe the `dispatch_semaphore_create` function is returning NULL even though it shouldn’t? Possibly a resource exhaustion of some kind in the OS due to heavy usage? 

Its difficult to go much further with this without a reproduction case, have you been able to reproduce it at will? Can you share any more details that might help us understand the conditions in which this is happening, or a cut down reproduction project if you had it. 

Also it does look like you are using a slightly older version of the library, it may be worth upgrading to the latest when convenient to see if it still happens.

**Comment by ericcj** [comment] 2023-06-16 15:43
we don't know any more than is here unfortunately, i'll keep you updated if we learn more it's a relatively small amount of sessions

**Comment by clr182** [comment] 2023-11-15 10:15
Hi,
As this issue hasn't seen any activity for some time I will be closing it out. Please feel free to reopen if there are any further questions.

**Closed by clr182** 2023-11-15 10:15 UTC
Labels: awaiting feedback
