### ISSUE TITLE
Provide an optional "Do Not Pull Stack" flag for Notify items

### ISSUE THREAD

**Issue by AaronSofaer** [bugsnag/bugsnag-cocoa#44] opened 2015-04-28 18:51 UTC
We've got an issue where some of the time, when we're firing Notify items, there's a crash in the OS's backtrace() flow. The crash on notify is in:

 `KSCrashSentry_User.c`, `kscrashsentry_reportUserException`, line 70: `callstackCount = backtrace((void**)callstack, callstackCount);`

We don't need the stack; in fact, we don't need anything other than the Notify item's bare minimum.

An example is here, if the dev team has access to our team's Bugsnags: https://bugsnag.com/plangrid/plangrid-ios/errors/550ac40e7c992b99ead0c2cb?event_id=553fcd69548678c57afed980

If not, I can send a copy of the relevant data; and I have attached a screenshot of the stack in case that proves to be helpful.

The underlying issue may be an Apple bug, but as there's no particular reason to expect the backtrace bug to be addressed (though we are filing it in Radar), we'd really like to be able to work around it so that we don't get spurious crashes.

![screenshot 2015-04-28 11 49 54](https://cloud.githubusercontent.com/assets/2935149/7377657/bbd1f94e-ed9c-11e4-81c1-f5dfd58cf274.png)

**Comment by snmaynard** [comment] 2015-05-21 00:10
Hey @AaronSofaer - apologies for the delay in looking at this.

Do you have a link to the radar ticket you have filed? Also what are you providing to the notifier to log - is it an exception that has been thrown or is it just an unthrown exception? Is it something that happens rarely or is it easy to reproduce for you?

It could be that the error doesnt have a stacktrace, and so the generated backtrace is used. I'm not sure that backtrace is crashing - because the trace is actually attached to the error report, but maybe you are seeing something I'm missing there.

**Comment by russbishop** [comment] 2015-05-21 17:38
It is the OS `backtrace()` call that is crashing. 

We're creating our own `NSException` instance but it is never thrown; we are just reporting a potential internal logic error not an actual crash in this case.

It would be nice to have a mechanism to notify without even creating an exception.

**Comment by snmaynard** [comment] 2015-05-21 17:40
@russbishop how do you know that the call is crashing?

**Comment by russbishop** [comment] 2015-05-21 18:01
@snmaynard Well because the secondary fail-safe snag shows the crashing line is `callstackCount = backtrace((void**)callstack, callstackCount);` in `KSCrashSentry_User.c` line 70.

**Comment by snmaynard** [comment] 2015-05-21 18:07
@russbishop But that backtrace could be attached to a report in the absence of a stacktrace being attached to the passed in exception.

One theory could be that the exception being passed in doesn't have its own stacktrace (because it wasn't thrown) so this backtrace is attached to the report instead. I'm just wondering if you have seen anything to confirm for sure that its a crash, and that its not just failing to extract the right information from the exception you pass in.

The backtrace call generates a stacktrace so it would be expected that in that case that the stacktrace would lead to the backtrace call.

I'm going to spend some time trying to reproduce the issue you are seeing, because something strange is definitely happening. The severity is set to error which does imply crash, but there is no error tab which would be present if there was a crash. I was just wondering if you had looked at it in any depth or were just basing it off the stacktrace resolving to the backtrace call?

**Comment by russbishop** [comment] 2015-05-21 20:23
@snmaynard I have investigated it in depth and the problem appears to be the original `notify` call eventually causes a crash in the original exception handler (a double fault). 

That triggers a second cycle through the mach exception handler which detects the crash is the result of trying to handle a previous crash and it does the basic "safe" report and we lose the details of the original report. 

So the result the end user experiences is a real hard app crash as a result of us having called `[Bugsnag notify ...]`.

It seems like there are two exception handlers running in some of the events related to this:

The primary handler thread:
`KSCrashSentry_MachException.c:231:0ksmachexc_i_handleExceptions`

The secondary double-fault thread:
`KSCrashSentry_MachException.c:223:0ksmachexc_i_handleExceptions`


I could be reading this all wrong, but if I am something else strange is happening because we get a lot of Warn/Info snags using this exact same code path and the vast majority come through as expected with no problems. It is only occasionally that get this crash.

**Comment by ConradIrwin** [comment] 2015-05-29 21:51
It sounds like there is a bug deep inside the library, but I'm not sure that the right fix is to add a flag. We still want to know where the notify was called.

One way to work around this might be to allow you to pass a custom stack trace so that we bypass that code-path, but I'd much rather get to the bottom of why there's a crash in the first place.

**Closed** 2016-02-16 21:36 UTC
