### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by EugeneFoo** [bugsnag/bugsnag-cocoa#1080] opened 2021-04-23 02:00 UTC
Hi, when I try add bugsnag in pod file, and do a clean install pod using:

<pre>
rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;
</pre>

And when I clean project and build in Xcode 12.4, this error occured:

![Screenshot 2021-04-23 at 9 57 24 AM](https://user-images.githubusercontent.com/7246280/115807299-f3b89f80-a41a-11eb-8841-e109dacd1a5e.png)

**Comment by johnkiely1** [comment] 2021-04-23 13:10
Hi @EugeneFoo 
Looks like you are trying to install `bugnag-cocoa` rather than `cocoapods-bugsnag` which is why I've transferred this issue. 

Would you mind sharing what your podfile looks like in this scenario?

Which version of Bugsnag are you trying to install? Perhaps you could try updating your podfile to use the latest v6.9.0 version as we did modify the code in the class the error is being reported from along with addressing some warnings.

**Comment by EugeneFoo** [comment] 2021-04-27 04:45
Hi @johnkiely1 ,

I did install using 
<pre>  pod 'Bugsnag' </pre>

The bugsnag run ok, but I wanna upload the dysm but it failed.
That's why I referring this guide:
https://docs.bugsnag.com/platforms/ios/symbolication-guide/

for without bitcode to automate the upload process.

But once I added this to podfile

<pre>
pod 'Bugsnag'
plugin 'cocoapods-bugsnag'
</pre>

when I build it will contains that error.

**Comment by mattdyoung** [comment] 2021-05-06 14:57
@EugeneFoo 
We're not able to reproduce this issue. Can you share the rest of your `Podfile`? What version of Bugsnag is showing in your `Podfile.lock`?

**Comment by mattdyoung** [comment] 2021-05-21 11:28
@EugeneFoo 
Closing this for now but if you're able to share a way for us to reproduce this issue happy to re-open and investigate further.

**Closed by mattdyoung** 2021-05-21 11:28 UTC
Labels: awaiting feedback
