### ISSUE TITLE
Bugsnag BreadCrumb is holding memory

### ISSUE THREAD

**Issue by x-henry-tian** [bugsnag/bugsnag-cocoa#436] opened 2019-11-21 00:06 UTC
**Issue**
Memory blocks are hold after BreadCrumb.Leave() call, it is an async call within a function from UnityEngine.ThreadPoolWorkQueue. Need help, thanks in advance.

**Version**
Bugsnag-Cocoa 5.22.10
Bugsnag-Unity Release v4.6.7(Happening on 4.6.4 too)
Xcode Version 11.2 (11B52)
Unity 2018.4.3f1 LTS

**Additional information**
Device: iPhoneX (IOS 13.2)
Objective-C ARC enabled.

<img width="640" alt="bugsnag zombie memory" src="https://user-images.githubusercontent.com/57972893/69288791-78144c80-0baf-11ea-9208-1c810441a4ba.png">

**Comment by mattdyoung** [comment] 2019-11-21 15:51
Hi @x-henry-tian 

Thanks for the report, we're just taking a look.

**Comment by x-henry-tian** [comment] 2019-11-25 21:53
I think I've tried following change, seems it works for me, at least not seeing any of those temporary block show in the allocation list.

<img width="1070" alt="Screen Shot 2019-11-25 at 1 52 56 PM" src="https://user-images.githubusercontent.com/57972893/69581185-efb8f180-0f8a-11ea-8f5a-05fed62dfdbd.png">

**Comment by mattdyoung** [comment] 2019-11-26 16:09
Hi @x-henry-tian 

We've been struggling to reproduce the behavior you describe with or without your change.

We tested this out by leaving hundreds of breadcrumbs both with/without your fix in a Cocoa example app. We didn't observe any difference in the macro-usage of memory.

We also visually inspected the codepath for adding a breadcrumb and couldn't spot anything obvious that would cause a memory leak. If there is a memory leak then it's probably caused by a block somewhere in the execution path holding onto a reference it shouldn't be and causing a retain cycle, but we haven't spotted anything suspicious along these lines.

There's also the possibility that there could be something specific to Unity apps that is causing this behavior.

Are you able to share a minimal reproduction case, so we can reproduce the behavior here and work out the best solution?

**Comment by x-henry-tian** [comment] 2019-11-26 18:34
Thanks for trying to look into this. Not exactly sure why this behavior is happening here, but a simple code patch we've done internally seems fixed this issue. I think it is because the Unity il2cpp threading is not creating the GC autoreleasing pool needed. Thanks for the awesome work.

Our code is just doing something like,

StartCoroutine(RecordCustomException());
...
IEnumerator RecordCustomException(string breadcrumb) {
      yield return new WaitForSeconds(0.1f);
      try
      {
        BugsnagUnity.Bugsnag.LeaveBreadcrumb( new Breadcrumb( "CustomExceptionBreadcrumb", BreadcrumbType.Error,
          new Dictionary<string, string>() { { "Details", breadcrumb } } ) );
      }
      catch ( Exception ex )
      {
        Log.Debug( "Exception while attempting to leave breadcrumb for RecordCustomException:\n{0}", ex );
      }
...
});

**Comment by mattdyoung** [comment] 2019-11-28 11:38
Hi @x-henry-tian 

Thanks for the update. We'll close this for now as we haven't been able to reproduce and you've managed to work around it in your case. If anyone finds a shareable reproduction case for this we can take another look.

Thanks!

**Closed by mattdyoung** 2019-11-28 11:38 UTC
