### ISSUE TITLE
[Question] OOM events excluded from 'session stability' metric in some SDK versions

### ISSUE THREAD

**Issue by jamieQ** [bugsnag/bugsnag-cocoa#1046] opened 2021-03-17 16:56 UTC
Hi! I was looking for some help diagnosing some discrepancies we've seen in our session stability metrics.

We recently updated our app from v6.3.0 to v6.6.0 and saw our stability metrics drop unexpectedly in subsequent releases. After investigating, it seemed that the session stability calculation for SDK version 6.3.0 _excludes_ likely OOM events from the score. #963 alludes to a regression introduced in v6.2.0 that removed session data from OOM events.

Could this bug have been responsible for behavior we observed? If not, are there any alternative explanations of our observations?

**Comment by yousif-bugsnag** [comment] 2021-03-18 10:07
Hey @jamieQ, 

Yes that's correct - the regression introduced in v6.2.0 meant that OOM events were incorrectly being excluded from stability scores due to the missing session data, and this was fixed in v6.5.1, so the lower scores you're seeing now are actually more representative of your app's stability.

I'm going to close this issue but if you have any further questions please feel free to reach out to us at support@bugsnag.com.

**Closed by yousif-bugsnag** 2021-03-18 10:07 UTC
