### ISSUE TITLE
StartWithConfig memory leak

### ISSUE THREAD

**Issue by jorgefrazaocosta** [bugsnag/bugsnag-cocoa#1641] opened 2024-03-22 14:54 UTC
### Describe the bug
When Bugsnag is initiated, Leaks tool says it catch a Memory Leak.

### Steps to reproduce
1. Implements 6.28.0 SDK
2. Start Bugsnag using `BugsnagConfiguration.loadConfig()` and set APIKey
3. Launch instruments
4. Observe memory leak

### Environment
* Bugsnag version: 6.28.0
* iOS/tvOS/macOS version(s): 17.3.1
* Simulator or physical device: iPhone 13 mini
* Xcode version: 15.2 or 15.3

<img width="1270" alt="Screenshot 2024-03-22 at 14 47 29" src="https://github.com/bugsnag/bugsnag-cocoa/assets/2707674/b72ee72a-1d94-4748-8f09-4fb7e36ef380">

**Comment by clr182** [comment] 2024-03-26 09:03
Hi @jorgefrazaocosta 
Thanks for reaching out. 

Can you please share a copy of your code for the BugSnag configuration with us for further investigation?

**Comment by clr182** [comment] 2024-03-28 11:30
Hi @jorgefrazaocosta 

I've passed this issue onto our engineering team who believe this does seem to be an issue on our side. We now have a backlog item aimed at investigating this further when priorities allow. Once we have more information to share we will be sure to reach out again with an update.

**Comment by n1tesh** [comment] 2024-04-13 10:52
@clr182 any update on this issue ?

**Comment by n1tesh** [comment] 2024-04-13 10:52
@clr182 any update on this issue ?

**Comment by mclack** [comment] 2024-05-08 15:46
Hi @jorgefrazaocosta and @n1tesh 

We have some ideas about what this issue may be caused by, but unfortunately we've been unable to reproduce this using the information provided so far.

Would either of you be able to share a stripped down reproduction application with us for further investigation? As this is a public thread, please feel free to share any further details with us directly by contacting support@bugsnag.com.

**Comment by clr182** [comment] 2024-06-13 13:55
Hi :wave:

As this thread has not seen any activity for some time I am going to close this issue out. 
If you would like to continue this investigation please reach out and we can reopen this issue.

**Closed by clr182** 2024-06-13 13:55 UTC
Labels: awaiting feedback, backlog
