### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by mark2b** [bugsnag/bugsnag-cocoa#1294] opened 2022-02-14 12:40 UTC
Existence of file **Framework/module.modulemap** causes to build failure by Carthage and by xcodebuild

### Steps to reproduce
1. Create Cartfile 
github "bugsnag/bugsnag-cocoa"
2. **carthage update --platform iOS --use-xcframeworks** 
    OR **xcodebuild archive -scheme Bugsnag-iOS**

`SOMEPATH/Carthage/Checkouts/bugsnag-cocoa/Framework/module.modulemap:1:18: error: 
      redefinition of module 'Bugsnag'
framework module Bugsnag {
                 ^

/HOME/Library/Developer/Xcode/DerivedData/Bugsnag-cqfcxofjpnufcjddvezkulwqbkjd/Build/Intermediates.noindex/ArchiveIntermediates/Bugsnag-iOS/BuildProductsPath/Release-iphoneos/Bugsnag.framework/Modules/module.modulemap:1:18: note: 
      previously defined here
framework module Bugsnag {
                 ^
1 error generated.
`

### Environment
* Bugsnag version: 6.16.2
* CocoaPods version: 1.11.2
* Carthage version (if any): 0.38.0
* iOS/tvOS/macOS version(s): 15.2

The workarounf is remove this file from filesystem and reference from projects build settings

**Comment by nickdowell** [comment] 2022-02-14 13:22
Hi @mark2b I have not been able to reproduce this locally, are you using different versions of the tools?

```
$ carthage version
0.38.0

$ xcodebuild -version
Xcode 13.2.1
Build version 13C100

$ echo 'github "bugsnag/bugsnag-cocoa"' > Cartfile

$ carthage update --platform iOS --use-xcframeworks
*** Cloning bugsnag-cocoa
*** Checking out bugsnag-cocoa at "v6.16.2"
*** xcodebuild output can be found in /var/folders/kw/bbtl7jr93mv010h6tfnlh73w0000gn/T/carthage-xcodebuild.hmlpme.log
*** Building scheme "BugsnagNetworkRequestPlugin-iOS" in Bugsnag.xcworkspace
*** Building scheme "Bugsnag-iOS" in Bugsnag.xcworkspace
```

**Comment by mark2b** [comment] 2022-02-14 14:54
Hi, I have exactly same versions.
May be one difference I build on Apple Silicon

**Comment by luke-belton** [comment] 2022-02-16 09:58
Hi @mark2b - we've also been unable to reproduce this on Apple Silicon. If you're able to share a cut-down example that reproduces the issue we'd be happy to investigate further. You can share this with us at support@bugsnag.com.

**Comment by mark2b** [comment] 2022-02-17 13:08
**% carthage version**
0.38.0

**% xcodebuild -version**
objc[99419]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1f4063678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1059c42c8). One of the two will be used. Which one is undefined.
objc[99419]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1f40636c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1059c4318). One of the two will be used. Which one is undefined.
Xcode 13.2.1
Build version 13C100

**% echo 'github "bugsnag/bugsnag-cocoa"' > Cartfile**
**% carthage update --platform iOS --use-xcframeworks**
*** Fetching bugsnag-cocoa
*** Checking out bugsnag-cocoa at "v6.16.2"
*** xcodebuild output can be found in /var/folders/w8/qgx_3tgs52z3mky1c78rjl200000gn/T/carthage-xcodebuild.Uyyz5F.log
*** Building scheme "Bugsnag-iOS" in Bugsnag.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/markb/Downloads/Carthage/Checkouts/bugsnag-cocoa/Bugsnag.xcworkspace -scheme Bugsnag-iOS -configuration Release -derivedDataPath /Users/markb/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/bugsnag-cocoa/v6.16.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/w8/qgx_3tgs52z3mky1c78rjl200000gn/T/bugsnag-cocoa SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/markb/Downloads/Carthage/Checkouts/bugsnag-cocoa)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/w8/qgx_3tgs52z3mky1c78rjl200000gn/T/carthage-xcodebuild.Uyyz5F.log

[carthage-xcodebuild.Uyyz5F.log](https://github.com/bugsnag/bugsnag-cocoa/files/8088831/carthage-xcodebuild.Uyyz5F.log)

**Comment by mattdyoung** [comment] 2022-03-18 11:31
Closing as we haven't been able to reproduce, but let us know if you can share a reproduction example so we can investigate further.

**Closed by mattdyoung** 2022-03-18 11:31 UTC
Labels: awaiting feedback
