### ISSUE TITLE
Version `1.11.2` of KSCrash (pinned with Bugsnag 5.7) causes deadlock while reporting user exceptions while sending reports 

### ISSUE THREAD

**Issue by anderscarling** [bugsnag/bugsnag-cocoa#143] opened 2017-04-18 17:27 UTC
Since [`KSCrash commit b1d8965 (released in 1.11.0)`](https://github.com/kstenerud/KSCrash/commit/b1d8965c4b93ff05c7c994722d6b8f768f78d5d1#diff-73fa199f522111237d50fffd9fb5aba7R100) added a call to `kscrs_getCrashReportPath` to `kscrash_i_onCrash` (in `KSCrashC.c`) is seems KSCrash will deadlock if an exception is recorded while `g_mutex` (in `KSCrashReportStore.c`) is held by another thread.

This seems to happen because exception recording suspends all other threads, including the one currently holding the `g_mutex`. This has a high-ish occurrence rate if you call `[Bugsnag notify:]` a few times in a row as `BugsnagNotifier notify:` ends with doing a `[self performSelectorInBackground:@selector(sendPendingReports) withObject:nil];`.

It seems this is fixed as a side effect of [`KSCrash commit 4899c8517 (released in 1.12.0)`]((https://github.com/kstenerud/KSCrash/commit/4899c8517f9561493bea1f4fc8bc80d55c6e5159) as it no longer claims `g_mutex` to get the path for the crash report.

I'm currently trying to build bugsnag-cocoa with kscrash 1.12.0 to validate that it actually fixes the issue..

**Comment by kattrali** [comment] 2017-04-18 17:36
Thanks for the report, @anderscarling. I'm in the process of testing against KSCrash 1.15.8 to fix this and some additional issues. There should be a release shortly.

**Comment by anderscarling** [comment] 2017-04-18 17:48
Nice @kattrali! Please let me know if you want me to test it against my project before you push the pod :)

It would be nice if new version of bugsnag-Cocoa exposed the new "logAllThreads" parameter of `KSCrash-reportUserException:`, freezing and dumping threads is definitely overkill in most of our use cases so would be nice to get rid of that overhead.

Anyhow, I can confirm that I'm deadlock free [using my 1.12.0  branch of bugsnag-cocoa](https://github.com/anderscarling/bugsnag-cocoa/tree/kscrash-1.12.0)

**Comment by kattrali** [comment] 2017-04-18 18:17
Awesome! Already got a patch in for `logAllThreads` as well. :)

**Comment by kattrali** [comment] 2017-04-18 20:33
@anderscarling I'll need to hold on this to investigate a regression in how KSCrash handles

**Comment by anderscarling** [comment] 2017-04-20 17:14
@kattrali Any progress? :)

**Comment by snmaynard** [comment] 2017-04-21 20:55
5.8 was released earlier that downgrades the version of KSCrash because of the newer versions we were seeing reliability issues with in testing. We are still planning on upgrading KSCrash, but upon seeing the issues with it we rolled back to the last known good version.

**Comment by anderscarling** [comment] 2017-04-24 12:18
ok, thanks!

**Comment by fractalwrench** [comment] 2017-10-06 09:11
Closing as we have forked an earlier version of KSCrash which does not cause a deadlock.

**Closed by fractalwrench** 2017-10-06 09:11 UTC
